###
GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}

###
PATCH http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}